version: "3.8"

services:
  lectures-app:
    # image: alexanderkov/lecturemanagement-app:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - redis
    ports:
      - "3000:3000"
    environment:
      # - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017
      - REDISDB_URI=redis://redis:6379

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
