version: "3.8"

services:
  lectures-app:
    # image: alexanderkov/lecturemanagement-app:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    # volumes:
      # - mongo-data:/data/db

# volumes:
  # mongo-data:
