version: "3.8"

services:
  lectures-app:
    # image: alexanderkov/lecturemanagement-app:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - redis
    ports:
      - "3000:3000"
    environment:
      # - NODE_ENV=production
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: School
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  redis-data:
  postgres-data:
